apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.import.endpoint: docker://quay.io/alitke/tinycore
    cdi.kubevirt.io/storage.import.source: registry
  labels:
    appname: vm-annotated-pvc-odr-metro
  name: sample-vm-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block
