apiVersion: cdi.kubevirt.io/v1beta1
kind: VolumeImportSource
metadata:
  name: cirros-source
spec:
  source:
      registry:
         url: "docker://quay.io/alitke/cirros:latest"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-vm-pvc
  labels:
    appname: vm-standalone-dv-odr-regional
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: cirros-source
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Block
