apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  labels:
    appname: vm-standalone-dv-odr-regional
  name: sample-vm
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - name: cloudinit
            disk: {}
          interfaces:
          - macAddress: 02:69:36:00:00:00
            masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - persistentVolumeClaim:
          claimName: sample-vm-pvc
        name: rootdisk
      - name: cloudinit
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: cirros
            password: drftw!
            chpasswd:
              expire: false
