---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: vm-standalone-pvc-k8s
  name: kubevirt-sub
spec:
    channel: kubevirt-samples/kubevirt-gitops
    placement:
      placementRef:
        kind: Placement
        name: kubevirt-placement
