---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-vm-pvc
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: cirros-source
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  storageClassName: rook-ceph-block
  volumeMode: Block
