---
resources:
  - source.yaml
  - pvc.yaml
  - vm.yaml
commonLabels:
  appname: kubevirt
secretGenerator:
- name: my-public-key
  files:
  - test_rsa.pub
generatorOptions:
  disableNameSuffixHash: true
