---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: sample-vm
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk: {}
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            # Match cirros-source memory requirements.
            # See https://github.com/cirros-dev/cirros/issues/53
            memory: 256Mi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-public-key
            propagationMethod:
              configDrive: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: sample-vm-pvc
        - name: cloudinit
          cloudInitConfigDrive:
            userData: |
              #!/bin/sh
              echo "Running user-data script"
